# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_osedev',
            field=models.BooleanField(default=True, help_text='Designates whether the user has been approved as an OSE Developer at some point in time.', verbose_name='OSEDev status'),
            preserve_default=False
        ),
        migrations.AlterField(
            model_name='user',
            name='is_osedev',
            field=models.BooleanField(default=False, help_text='Designates whether the user has been approved as an OSE Developer at some point in time.', verbose_name='OSEDev status'),
        ),
    ]
