# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


def update_user_status(apps, schema_editor):
    User = apps.get_model("user", "User")
    for user in User.objects.all():
        user.is_active = True
        user.is_osedev = True
        if user.email.startswith('invalid'):
            user.is_current = False
        else:
            user.is_current = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170913_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Requires that OSE Developer status is also checked. Active OSE Developer is someone who is currently an active contributor to OSE.', verbose_name='Current'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates this as a valid user account (eg. not spammer or fake). Un-checking this will prevent user from being able to login and is preferable to deleting accounts.', verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_osedev',
            field=models.BooleanField(default=False, help_text='Designates whether the user has been approved as an OSE Developer at some point in time. Adds their logged time to global development effort.', verbose_name='OSE Developer'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Used with Google Maps API to get a lat/long for mapping contributors.', max_length=512, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_details',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.RunPython(update_user_status)
    ]
