# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def add_confabulator(apps, schema_editor):
    from datetime import timedelta
    Product = apps.get_model("plm", "Product")
    Progress = apps.get_model("plm", "Progress")
    confabulator = Product.objects.create(
        name="Confabulator",
        spreadsheet="10V7IqQuUbWgV8wilXdbyjwvbfqcliI0-2b8vPAbr-H4"
    )
    today = django.utils.timezone.localdate()
    for i in range(101):
        progress = Progress.objects.create(
            product=confabulator,
            day=today - timedelta(i),
            complete=100 - i
        )
        if progress.complete == 100:
            confabulator.progress = progress
            confabulator.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.IntegerField(verbose_name='Percent Complete')),
                ('day', models.DateField(default=django.utils.timezone.localdate)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-day',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plm.Part')),
                ('category', models.CharField(choices=[('habitat', 'Habitat'), ('agriculture', 'Agriculture'), ('industry', 'Industry'), ('energy', 'Energy'), ('materials', 'Materials'), ('transport', 'Transportation'), ('domestic', 'Domestic'), ('component', 'Component')], default='component', max_length=128, verbose_name='Category')),
                ('spreadsheet', models.CharField(max_length=512, verbose_name='Google Sheet ID')),
                ('cell', models.CharField(default="'Dev'!D47", max_length=512, verbose_name='Cell')),
            ],
            bases=('plm.part',),
        ),
        migrations.AddField(
            model_name='progress',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='plm.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='plm.Progress'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set([('product', 'day')]),
        ),
        migrations.RunPython(add_confabulator)
    ]
