# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
