# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import jsonfield.fields
import yamlfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField(null=True)),
                ('state', django_fsm.FSMField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('live', 'Live')], default='draft', max_length=50)),
            ],
            options={
                'verbose_name': 'Application Form',
                'verbose_name_plural': 'Application Forms',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('submitted', models.DateTimeField(null=True)),
                ('reviewed', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('state', django_fsm.FSMField(choices=[('created', 'Not Started'), ('started', 'Started'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('declined', 'Declined')], default='created', max_length=50)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=512)),
                ('instructions', models.TextField(blank=True)),
                ('widget_type', models.CharField(choices=[('Questions', 'Questions')], default='Questions', max_length=128, verbose_name='Widget Type')),
                ('widget_conf', yamlfield.fields.YAMLField(blank=True, verbose_name='Widget Configuration')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='onboarding.Application')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='StepValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', jsonfield.fields.JSONField(null=True)),
                ('is_acceptable', models.BooleanField(default=False)),
                ('application_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='onboarding.ApplicationInstance')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='onboarding.Step')),
            ],
            options={
                'ordering': ('step__number',),
            },
        ),
    ]
